Fix some errors in the backup script for xcat.org

diff --git a/backup/runbackup b/backup/runbackup
--- a/backup/runbackup
+++ b/backup/runbackup
@@ -23,10 +23,16 @@ if [[ -d ${BACKUP_DIRECTORY} ]]; then
 
     LOGIT "Displaying existing backups:" 
     LOGIT "======================================================="
-    ls -ltrh ${BACKUP_DIRECTORY}/*.tar.gz >> ${LOGFILE}
+    ls -ltrh ${BACKUP_DIRECTORY}/*.tar.gz >>  ${LOGFILE} 2>&1
     LOGIT "======================================================="
 
-    scp backup_xcat.org.sh ${TARGET}:${TARGET_DIR}
+    BACKUP_SCRIPT="$(dirname ${SCRIPT})/backup_xcat.org.sh"
+    if [[ ! -x ${BACKUP_SCRIPT} ]]; then
+        echo "Cound not find the ${BACKUP_SCRIPT}, cannot continue!"
+        exit 1
+    fi
+
+    scp ${BACKUP_SCRIPT} ${TARGET}:${TARGET_DIR}
 
     LOGIT "Executing backup..."
     ssh ${TARGET} ${TARGET_DIR}/backup_xcat.org.sh
@@ -42,7 +48,8 @@ if [[ -d ${BACKUP_DIRECTORY} ]]; then
     ls -ltrh ${BACKUP_DIRECTORY}/*.tar.gz >> ${LOGFILE}
     LOGIT "======================================================="
 else 
-    echo "ERROR! DIRECTORY DOES NOT EXIST! PLEASE CHECK SCRIPT!" >> ${LOGFILE}
+    echo "ERROR! DIRECTORY FOR BACKUP DOES NOT EXIST: ${BACKUP_DIRECTORY}"
+    exit 1
 fi 
 
 
